# Generated by Django 4.1 on 2023-08-03 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Primeiro nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('phone', models.CharField(max_length=11, verbose_name='Celular')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('service', models.IntegerField(choices=[(0, 'Instalações Elétricas Residenciais e Prediais'), (1, 'Infraestrutura de Cabeamento Estruturado'), (2, 'Automação Residencial'), (3, 'SPDA'), (4, 'Medição Agrupada')], verbose_name='Serviço')),
                ('return_way', models.IntegerField(choices=[(0, 'WhatsApp'), (1, 'E-mail')], verbose_name='Forma de retorno')),
            ],
        ),
    ]
