# Generated by Django 4.1 on 2023-08-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetform',
            options={'verbose_name': 'Formulário de orçamento', 'verbose_name_plural': 'Formulários de orçamentos'},
        ),
    ]
