# Generated by Django 4.1 on 2023-08-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetform',
            options={'verbose_name': 'Formulário de orçamento', 'verbose_name_plural': 'Formulários de orçamentos'},
        ),
        migrations.AddField(
            model_name='budgetform',
            name='description',
            field=models.EmailField(default='teste', max_length=500, verbose_name='Descrição'),
            preserve_default=False,
        ),
    ]
