# Generated by Django 4.1 on 2023-08-08 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_budgetform_options_budgetform_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetform',
            name='description',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='budgetform',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
